<div id="content_header"><h2>Reporting - Pemasukan</h2></div>
<hr>
<?php
//print_r($this->data);
echo '<br/>';
echo 'Period Report: <b>'.$this->startdate. '</b> to <b>'.$this->enddate.'</b>';
echo '<br/><br/>';
//echo count($this->data);
if(count($this->data) > 0){
    foreach ($this->data as $idx => $branchData) {
        if(count($this->data) > 1) echo ($idx+1).'. ';
        echo 'Cabang : ' . $branchData['branch']['name'].'<br/>';
        ?>
    <table id="table_list" cellspacing="1" cellpadding="5">
    <thead>
        <tr bgcolor="#FFFFFF">
            <td colspan="12">&nbsp;</td>
        </tr>
    </thead>
    <tbody>
        <tr bgcolor="#d6d6d6">
            <td align="center" width="10">No.</td>
            <td align="center" width="100">Order No.</td>
            <td align="center" width="200">Order Date</td>
            <td align="center" width="150">Customer Name</td>
            <td align="center" width="100">Telephone</td>
            <td align="center" width="100">Total(Rp)</td>
            <td align="center" width="50">Action</td>
        </tr>
        <?php
        $grandTotal = 0;
        if(count($branchData['data']) > 0){
            $i=0;
            foreach ($branchData['data'] as $idx1 => $data){
                $i++;
                $grandTotal += $data['total'];
                if($i%2 == 0) $bgcolor = "#e6e6fa";
                else $bgcolor = "#f1f0f0";
                ?>
            <tr bgcolor="<?php echo $bgcolor; ?>">
                <td align="left"><?php echo $i; ?></td>
                <td align="left"><?php echo $data['orderno']; ?></td>
                <td align="left"><?php echo $data['orderdate']; ?></td>
                <td align="left"><?php echo $data['customername']; ?></td>
                <td align="left"><?php echo $data['phone']; ?></td>
                <td align="right"><?php echo $data['total']; ?></td>
                <td align="center"><a href="#" onclick="javascript: return showDetail(<?php echo $data['id']; ?>);">Detail</a></td>
            </tr>
                <?php
            }
        }
        else{
            ?>
        <tr bgcolor="#f1f0f0" style="color : red;">
            <td align="center" colspan="12"><b>No data to display</b></td>
        </tr>
            <?php
        }
        ?>
    </tbody>
        <tr>
            <td colspan="5" align="right">Total :</td>
            <td style="color: red;" align="right"><?php echo $grandTotal; ?></td>
        </tr>
    </table>
    <br/><br/>
    <?php
    }
}
?>
<div id="detailDialog"></div>
<script type="text/javascript">
    function showDetail(orderid) {
        url = '/rptpemasukan/viewdetail/orderid/' + orderid;
        $('#detailDialog').load(url).dialog({
            modal   : true,
            width   : 800,
            height  : 600,
            button  : 'close'
        });
        return false;
    }
</script>