
<div id="content_header"><h2>Master - Role</h2><div style="float:right"><h2 id="form_type"><?php echo $this->strFormType;?> Record</h2></div></div>
<hr>
<div id="tabs">
    <form id="form" method="POST" action="/role/save" class="form_element" enctype="multipart/form-data" target="form_iframe">
        <ul>
            <li><a href="#tabs-details">Details</a></li>
            <li><a href="#tabs-rights">Access Rights</a></li>
        </ul>
        <div id="tabs-details">
            <table id="table_form">
                <tr>
                    <td>Role ID</td>
                    <td><input type="text" name="ID" id="ID" size="10" readonly value="<?php echo $this->strID;?>" class="<?php if ($this->strFormType == "Edit") {echo "readonly ";}?>text"></td>
                </tr>
                <tr>
                    <td>Role Name * </td>
                    <td><input type="text" name="RoleName" id="RoleName" size="20" value="<?php echo $this->RoleName ?>" class="text required"></td>
                </tr>
                <tr>
                    <td>Description</td>
                    <td><input type="text" name="Description" id="Description" size="50" value="<?php echo $this->Description ?>" class="text"></td>
                </tr>
            </table>
        </div>
        <div id="tabs-rights">
            <table class="table_form">
                <tr>
                    <td colspan="3"><h2>Master</h2></td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="branch" <?php if(array_search("branch", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Branch</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="role" <?php if(array_search("role", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Role</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="employee" <?php if(array_search("employee", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Employee</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="product" <?php if(array_search("product", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Product</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="stock" <?php if(array_search("stock", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Stock</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="user" <?php if(array_search("user", $this->Rights) != false){echo "checked";}?>></td>
                    <td>User</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="news" <?php if(array_search("news", $this->Rights) != false){echo "checked";}?>></td>
                    <td>News</td>
                </tr>
                <tr>
                    <td colspan="3"><h2>Transaction</h2></td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="trnorder" <?php if(array_search("trnorder", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Order</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="trnorderassignment" <?php if(array_search("trnorderassignment", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Order Assignment</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="trnfinishorder" <?php if(array_search("trnfinishorder", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Finish Order</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="trnservice" <?php if(array_search("trnservice", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Service</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="trnserviceassignment" <?php if(array_search("trnserviceassignment", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Service Assignment</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="trnfinishservice" <?php if(array_search("trnfinishservice", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Finish Service</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="trnpenggunaanbahan" <?php if(array_search("trnpenggunaanbahan", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Using of Raw Material</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="trnsalesorder" <?php if(array_search("trnsalesorder", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Sales Order</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="trnpurchasesorder" <?php if(array_search("trnpurchasesorder", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Purchases Order</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="trnkasharian" <?php if(array_search("trnkasharian", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Daily Cash</td>
                </tr>
                <tr>
                    <td colspan="3"><h2>Reports</h2></td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="rptpembelanjaan" <?php if(array_search("rptpembelanjaan", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Pembelanjaan</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="rptgaji" <?php if(array_search("rptgaji", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Gaji Pegawai</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="rptbiayaoperasional" <?php if(array_search("rptbiayaoperasional", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Biaya Operasional</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="rptpemasukan" <?php if(array_search("rptpemasukan", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Pemasukan</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="rptrugilaba" <?php if(array_search("rptrugilaba", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Rugi laba</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="rptstockopname" <?php if(array_search("rptstockopname", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Stock op name</td>
                </tr>
                <tr>
                    <td colspan="3"><h2>Maintenance</h2></td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="exportdata" <?php if(array_search("exportdata", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Export Data</td>
                </tr>
                <tr>
                    <td> &nbsp; </td>
                    <td><input type="checkbox" name="Rights[]" id="Rights[]" value="setting" <?php if(array_search("setting", $this->Rights) != false){echo "checked";}?>></td>
                    <td>Setting</td>
                </tr>
            </table>
        </div>
    <hr>
    <div id="form_save_result" class="form_save_success">Save successful</div>
    <input type="hidden" name="type" id="type" value="<?php echo $this->strFormType; ?>">
    <input type="submit" value="Save" id="btn_save" class="button">
    <input type="button" value="New" id="btn_new" class="button" onclick="window.location='/role/form/type/add'">
    <input type="button" value="Delete" id="btn_delete" class="button">
    <input type="button" value="Close" id="btn_close" onclick="window.location='/role'" class="button">
    </form>
    <iframe id="form_iframe" name="form_iframe" src="" style="width:100%;height:100px;border:0 solid #FFFFFF;"></iframe>
</div>

<div id="dialog-modal" title="Attention" style="display:none"></div>

<div id="dialog-confirm" title="Delete record?" style="display:none">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This record will be permanently deleted and cannot be recovered. Are you sure?</p>
</div>
<script type="text/javascript">
    $('#btn_delete').click(function() {
        if ($('#type').val() == "Add") {
            return;
        }

    	$( "#dialog-confirm" ).dialog({
    		resizable: false,
    		height:200,
    		modal: true,
    		buttons: {
    			"Delete record": function() {
    				$( this ).dialog("close");
    				$.get("/role/save/type/Delete/ID/" + $('#ID').val(), function() {
    				    window.location = '/branch';
    				});
    			},
    			Cancel: function() {
    				$( this ).dialog("close");
    			}
    		}
    	});
    });

    var strRoleID = $('#ID').val();

    $( "#tabs" ).tabs();
    $("#form").validate();
</script>
