<script>
    $(document).ready(function() {
        $('#main_menu').accordion({autoHeight: false});
        $('#table_list').dataTable({
            "bJQueryUI": true,
            "bServerSide": true,
            "sServerMethod": "POST",
            "sPaginationType": "full_numbers",
            "sAjaxSource": "/role/data"
        });

        $('#table_list tbody tr').live('dblclick', function () {
                var sTitle;
                var nTds = $('td', this);
                var strID = $(nTds[0]).text();

                window.location='/role/form/type/edit/id/' + strID;
        });
    });
</script>

<form class="form_element">
<div id="content_header"><h2>Master - Role <?php echo $this->test;?></h2></div>
<div style="float:right;padding-bottom:5px">
    <input type="button" value="Create New Record" onclick="window.location='/role/form/type/add'" class="button">
</div>
<hr>

<table id="table_list">
    <thead>
        <tr>
            <td>Role ID</td>
            <td>Role Name</td>
            <td>Description</td>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
</form>