<script type="text/javascript">
    $(document).ready(function() {
        $('#main_menu').accordion({autoHeight: false});
        $('#table_list').dataTable({
            "bJQueryUI": true,
            "bServerSide": true,
            "sServerMethod": "POST",
            "sPaginationType": "full_numbers",
            "sAjaxSource": "/product/data"
        });

        $('#table_list tbody tr').live('dblclick', function () {
                var sTitle;
                var nTds = $('td', this);
                var strID = $(nTds[0]).text();

                window.location='/product/form/type/edit/id/' + strID;
        });
    });
</script>

<form class="form_element" action="">
<div id="content_header"><h2>Master - Product</h2></div>
<div style="float:right;padding-bottom:5px">
    <input type="button" value="Create New Record" onclick="window.location='/product/form/type/add'" class="button">
</div>
<hr>

<table id="table_list">
    <thead>
        <tr>
            <td>Product ID</td>
            <td>Product Code</td>
            <td>Product Name</td>
            <td>Type</td>
            <td>Size</td>
            <td>Color</td>
            <td>Material</td>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
</form>