<div id="content_header"><h2>Transaction - Daily Cash</h2><div style="float:right"><h2 id="form_type"><?php echo $this->strFormType;?> Record</h2></div></div>
<hr>

<form id="form" method="POST" action="/trnkasharian/save" class="form_element" enctype="multipart/form-data" target="form_iframe">

    <table id="table_form">
        <tr>
            <td>Trn. ID</td>
            <td><label for="ID"></label><input type="text" name="ID" id="ID" size="20" readonly value="<?php echo $this->strID;?>" class="readonlytext"></td>
        </tr>
        <tr>
            <td>Branch ID</td>
            <td><label for="BranchID"></label><input type="text" name="BranchID" id="BranchID" size="20" readonly value="<?php echo $_SESSION['BranchID'];?>" class="readonlytext"></td>
        </tr>
        <tr>
            <td>Trn. No</td>
            <td><label for="TrnNo"></label> <input type="text" name="TrnNo" id="TrnNo" size="20" readonly size="10" value="<?php echo ($this->strFormType == 'Edit') ? $this->TrnNo : 'Auto Generate' ?>" class="readonlytext"></td>
        </tr>
        <tr>
            <td>Trn. Date</td>
            <td><label for="TrnDate"></label> <input type="text" name="TrnDate" id="TrnDate" size="20" readonly value="<?php echo ($this->strFormType == 'Edit') ? $this->TrnDate : 'Auto Generate' ?>" class="readonlytext"></td>
        </tr>
        <tr>
            <td>Description</td>
            <td><label for="Description"></label><input type="text" name="Description" id="Description" size="20" value="<?php echo ($this->strFormType == 'Edit') ? $this->Description : '' ?>" class="readonlytext"></td>
        </tr>
        <tr>
            <td>Debit</td>
            <td><label for="Debit"></label><input type="text" name="Debit" id="Debit" size="20" value="<?php echo ($this->strFormType == 'Edit') ? $this->Debit : '' ?>" class="readonlytext"></td>
        </tr>
        <tr>
            <td>Credit</td>
            <td><label for="Credit"></label><input type="text" name="Credit" id="Credit" size="20" value="<?php echo ($this->strFormType == 'Edit') ? $this->Credit : '' ?>" class="readonlytext"></td>
        </tr>
    </table>
    <br/>
<hr>
<div id="form_save_result" class="form_save_success">Save successful</div>
<input type="hidden" name="type" id="type" value="<?php echo $this->strFormType; ?>">
<input type="hidden" id="numrows" name="numrows" value="<?php echo $this->NumRows ?>">
<input type="submit" value="Save" id="btn_save" class="button">
<input type="button" value="New" id="btn_new" class="button" onclick="window.location='/trnkasharian/form/type/add'">
<input type="button" value="Delete" id="btn_delete" class="button">
<input type="button" value="Close" id="btn_close" onclick="window.location='/trnkasharian'" class="button">
</form>
<iframe id="form_iframe" name="form_iframe" src="" style="width:100%;height:200px;border:0px solid #FFFFFF;"></iframe>

<div id="dialog-modal" title="Attention" style="display:none"></div>

<div id="dialog-confirm" title="Delete record?" style="display:none">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This record will be permanently deleted and cannot be recovered. Are you sure?</p>
</div>
<?php
//print_r($this->Items);
?>
<script type="text/javascript">
    $('#btn_delete').click(function() {
        if ($('#type').val() == "Add") {
            return;
        }

        $( "#dialog-confirm" ).dialog({
            resizable: false,
            height:200,
            modal: true,
            buttons: {
                "Delete record": function() {
                    $( this ).dialog("close");
                    $.get("/trnkasharian/save/type/Delete/ID/" + $('#ID').val(), function() {
                        window.location = '/trnkasharian';
                    });
                },
                Cancel: function() {
                    $( this ).dialog("close");
                }
            }
        });
    });

    var strTrnID = $('#ID').val();

    $("#form").validate();
</script>