<script type="text/javascript">
    function showLookup(view) {
        //alert('asd');
        url = '/lookup/' + view;
        $('#lookup').load(url).dialog({
            modal   : true,
            width   : 1024,
            height  : 600,
            button  : 'close',
            closeText: 'Close'
        });
        return false;
    }
</script>
<div id="content_header"><h2>Transaction - Order Assignment</h2><div style="float:right"><h2 id="form_type"><?php echo $this->strFormType;?> Record</h2></div></div>
<hr>

<form id="form" method="POST" action="/trnorderassignment/save" class="form_element" enctype="multipart/form-data" target="form_iframe">

    <table id="table_form">
        <tr>
            <td>Assignment ID</td>
            <td><label for="ID"></label><input type="text" name="ID" id="ID" size="20" readonly value="<?php echo $this->strID;?>" class="text"></td>
        </tr>
        <tr>
            <td>Branch ID</td>
            <td><label for="BranchID"></label><input type="text" name="BranchID" id="BranchID" size="20" readonly value="<?php echo $_SESSION['BranchID'];?>" class="text"></td>
        </tr>
        <tr>
            <td>Order ID</td>
            <td>
                <label for="OrderId"></label><input type="text" name="OrderId" id="OrderId" size="20" readonly size="10" value="<?php echo ($this->strFormType == 'Edit') ? $this->OrderId : '' ?>" class="text required">
                <input type="button" name="orderLookup" id="orderLookup" value="Order Lookup" onclick="javascript:return showLookup('order');">
            </td>
        </tr>
        <tr>
            <td>Order No</td>
            <td><label for="OrderNo"></label><input type="text" name="OrderNo" id="OrderNo" size="20" readonly value="<?php echo ($this->strFormType == 'Edit') ? $this->OrderNo : '' ?>" class="text required"></td>
        </tr>
        <tr>
            <td>Assignment Date</td>
            <td><label for="AssignmentDate"></label> <input type="text" name="AssignmentDate" id="AssignmentDate" size="20" readonly value="<?php echo ($this->strFormType == 'Edit') ? $this->AssignmentDate : 'Auto Generate' ?>" class="text"></td>
        </tr>
        <tr>
            <td>Employee ID</td>
            <td>
                <label for="EmployeeId"></label><input type="text" name="EmployeeId" readonly id="EmployeeId" size="20" value="<?php echo ($this->strFormType == 'Edit') ? $this->EmployeeId : '' ?>" class="text required">
                <input type="button" name="employeeLookup" id="employeeLookup" value="Employee Lookup" onclick="javascript:return showLookup('employee');">
            </td>
        </tr>
        <tr>
            <td>Employee Name</td>
            <td>
                <label for="EmployeeName"></label><input type="text" name="EmployeeName" readonly id="EmployeeName" size="20" value="<?php echo ($this->strFormType == 'Edit') ? $this->EmployeeName : '' ?>" class="text required"></td>
        </tr>
        <tr>
            <td>Price</td>
            <td>
                <label for="Price"></label><input type="text" name="Price" id="Price" size="20" value="<?php echo ($this->strFormType == 'Edit') ? $this->Price : '' ?>" class="text required"></td>
        </tr>
    </table>
<hr>
<div id="form_save_result" class="form_save_success">Save successful</div>
<input type="hidden" name="type" id="type" value="<?php echo $this->strFormType; ?>">
<input type="submit" value="Save" id="btn_save" class="button">
<input type="button" value="New" id="btn_new" class="button" onclick="window.location='/trnorderassignment/form/type/add'">
<input type="button" value="Delete" id="btn_delete" class="button">
<input type="button" value="Close" id="btn_close" onclick="window.location='/trnorderassignment'" class="button">
</form>
<iframe id="form_iframe" name="form_iframe" src="" style="width:100%;height:200px;border:0px solid #FFFFFF;"></iframe>

<div id="dialog-modal" title="Attention" style="display:none"></div>

<div id="dialog-confirm" title="Delete record?" style="display:none">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This record will be permanently deleted and cannot be recovered. Are you sure?</p>
</div>

<div id="lookup" title="Lookup"></div>

<script type="text/javascript">
    $('#btn_delete').click(function() {
        if ($('#type').val() == "Add") {
            return;
        }

        $( "#dialog-confirm" ).dialog({
            resizable: false,
            height:200,
            modal: true,
            buttons: {
                "Delete record": function() {
                    $( this ).dialog("close");
                    $.get("/trnorderassignment/save/type/Delete/ID/" + $('#ID').val(), function() {
                        window.location = '/trnorderassignment';
                    });
                },
                Cancel: function() {
                    $( this ).dialog("close");
                }
            }
        });
    });

    var strAssignmentID = $('#ID').val();

    $("#form").validate();
</script>