<div id="nota-penjualan">
    <span style="font-size: 20px;font-weight: bold;">TOKO JAKET KULIT KALONG</span>
    <table width="100%">
        <tr>
            <td width="70%" valign="top">
                Work Shop : Jl. Raya Kd. Halang, No. 189 - Bogor <br/>
                Telp. (0251) 8659807. <br/>
                HP. 0813 1639 8419 <br/>
                Pin BB : 256918CD
            </td>
            <td valign="top" nowrap="">
                Kepada Yth. <br/>
                Nama : <?php echo $this->CustomerName;?> <br/>
                Telp : <?php echo $this->Phone;?> <br/><br/>
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td style="font-size: 20px;font-weight: bold;">Nota Service</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td style="font-size: 16px;font-weight: bold;">No: <?php echo $this->TrnNo;?></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>Tanggal: <?php echo date('d-m-Y');?></td>
        </tr>
    </table>
    <br/>
    <table width="100%" cellpadding="3">
        <tr bgcolor="#e6e6fa">
            <td width="250">Nama Barang</td>
            <td>Ukuran</td>
            <td>Warna</td>
            <td>Bahan</td>
            <td>Harga</td>
            <td>Qty</td>
            <td>Total</td>
        </tr>
    <?php
        $grandtotal = 0;
        foreach($this->Items as $idx => $item) {
    ?>
        <tr>
            <td><?php echo $item['productname'];?></td>
            <td><?php echo $item['sizename'];?></td>
            <td><?php echo $item['colorname'];?></td>
            <td><?php echo $item['materialname'];?></td>
            <td align="right"><?php echo $item['price'];?></td>
            <td align="right"><?php echo $item['amount'];?></td>
            <td align="right"><?php echo $item['total'];?></td>
        </tr>
    <?php
            $grandtotal += $item['total'];
        }
    ?>
        <tr bgcolor="aqua">
            <td colspan="6" align="right">Grand Total</td>
            <td align="right"><span id="grandtotal" style="color: red;text-align: right;"><?php echo $grandtotal;?></span></td>
        </tr>
        <tr>
            <td colspan="6" align="right">DP</td>
            <td align="right"><span id="dp" style="color: red;text-align: right;"><?php echo $this->Dp;?></span></td>
        </tr>
        <tr>
            <td colspan="6" align="right">Sisa</td>
            <td align="right" style="border-top: solid 1px #000099;"><span id="sisa" style="color: red;text-align: right;"><?php echo $grandtotal - $this->Dp;?></span></td>
        </tr>
    </table>
    <b>Ukuran sbb:</b>
    <br/><br/>
    1. Jaket
    <table>
        <tr><td>- Bahu/Shoulder</td><td>&nbsp;&nbsp;:</td></tr>
        <tr><td>- P. Lengan/Sleeve Length</td><td>&nbsp;&nbsp;:</td></tr>
        <tr><td>- Lingkar Dada/Chest</td><td>&nbsp;&nbsp;:</td></tr>
        <tr><td>- Pinggang/Waist</td><td>&nbsp;&nbsp;:</td></tr>
        <tr><td>- Pinggul/Hip</td><td>&nbsp;&nbsp;:</td></tr>
        <tr><td>- P. Badan/Length</td><td>&nbsp;&nbsp;:</td></tr>
        <tr><td>- Manset/Cuff</td><td>&nbsp;&nbsp;:</td></tr>
        <tr><td>- Kerong Lengan/A.H.</td><td>&nbsp;&nbsp;:</td></tr>
        <tr><td>- Kerong Leher/N.H.</td><td>&nbsp;&nbsp;:</td></tr>
    </table>
    <br/>
    2. Celana/Rok
    <table>
        <tr><td>- Bahu/Shoulder</td><td>&nbsp;&nbsp;:</td></tr>
        <tr><td>- P. Lengan/Sleeve Length</td><td>&nbsp;&nbsp;:</td></tr>
        <tr><td>- Lingkar Dada/Chest</td><td>&nbsp;&nbsp;:</td></tr>
        <tr><td>- Pinggang/Waist</td><td>&nbsp;&nbsp;:</td></tr>
        <tr><td>- Pinggul/Hip</td><td>&nbsp;&nbsp;:</td></tr>
        <tr><td>- P. Badan/Length</td><td>&nbsp;&nbsp;:</td></tr>
        <tr><td>- Manset/Cuff</td><td>&nbsp;&nbsp;:</td></tr>
        <tr><td>- Kerong Lengan/A.H.</td><td>&nbsp;&nbsp;:</td></tr>
        <tr><td>- Kerong Leher/N.H.</td><td>&nbsp;&nbsp;:</td></tr>
    </table>
</div>
<br/><br/><br/>
<a href="#" id="btnCetak">Cetak</a> | <a href="/trnservice">Cancel</a>
<script type="text/javascript">
    $('#btnCetak').click(function(){
        $('#nota-penjualan').printElement();
    });
</script>