<!DOCTYPE html>
<html>
    <head>
        <title>ACC Branch Traffic Information System</title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <link type="text/css" href="/css/smoothness/jquery-ui-1.8.19.custom.css" rel="Stylesheet" />
        <link type="text/css" href="/css/jquery.dataTables.css" rel="Stylesheet" />
        <link type="text/css" href="/css/jquery.dataTables_themeroller.css" rel="Stylesheet" />
        <link type="text/css" href="/css/style.css" rel="Stylesheet" />
        <script type="text/javascript" src="/js/jquery-1.7.2.min.js"></script>
        <script type="text/javascript" src="/js/jquery-ui-1.8.19.custom.min.js"></script>
        <script type="text/javascript" src="/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="/js/main.js"></script>
        <script type="text/javascript" src="/js/jquery.zend.jsonrpc.js"></script>
        <script type="text/javascript" src="/js/urlEncode.js"></script>
    </head>
    <body>
        <table width="100%" height="100%" id="main_container">
            <tr>
                <td id="pane_top">
                    <table border="0" cellpadding="0" cellspacing="0">
                        <tr>
                            <td><img src="/images/logo.png"></td>
                            <td valign="bottom" style="padding-bottom:15px;"><h1>Queuing System</h1></td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <?php echo $this->layout()->content; ?>
                </td>
            </tr>
            <tr>
                <td id="pane_bottom"><b>Astra Credit Companies 2012</b></td>
            </tr>
        </table>
    </body>
    <script>
        $(".button").button();
    </script>
</html>
